package cn.yejj.yejjrpc.demo.provider;

import cn.yejj.yejjrpc.core.annotation.YejjProvider;
import cn.yejj.yejjrpc.core.api.RpcRequest;
import cn.yejj.yejjrpc.core.api.RpcResponse;
import cn.yejj.yejjrpc.core.provider.ProviderBootstrap;
import cn.yejj.yejjrpc.core.provider.ProviderConfig;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.Resource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@RestController
@Import(ProviderConfig.class)
public class YejjrpcDemoProviderApplication {

    public static void main(String[] args) {
        SpringApplication.run(YejjrpcDemoProviderApplication.class, args);
    }

    @Autowired
    ProviderBootstrap providerBootstrap;

    //使用HTTP + JSON 实现序列化和通信
    @RequestMapping("/")
    public RpcResponse invoke(@RequestBody RpcRequest request) {
        RpcResponse response = new RpcResponse();

        return response;
    }

    private RpcResponse invokeRequest(RpcRequest request) {
        Object bean = providerBootstrap.getSkeletonMap().get(request.getService());
        try {
            Method method =getMethod(bean.getClass(),request.getMethod());
            Object result = method.invoke(bean, request.getArgs());
            return new RpcResponse(true,result);
        } catch ( InvocationTargetException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

    private Method getMethod(Class<?> aClass, String method) {
        for (Method m : aClass.getDeclaredMethods()) {
            if (m.getName().equals(method)) {
                return m;
            }
        }
        return null;
    }



    //ApplicationRunner 用于在Spring Boot应用程序启动后执行一些特定的代码
    @Bean
    ApplicationRunner providerRunner() {
        return args -> {
            RpcRequest request = new RpcRequest();
            request.setService("cn.yejj.yejjrpc.demo.api.UserService");
            request.setMethod("findById");
            request.setArgs(new Object[]{100});

            RpcResponse response = invokeRequest(request);
            System.out.println(response.getResult());
        };
    }


}
